import { IObject } from "@iote/bricks";

/**
 * A course is a structured and organized set of learning activities that 
 *    are designed to achieve a specific learning outcome or objective.
 * 
 * A course can contain one or more Assignable Units also known as learning
 *  activities
 * 
 * In this interface we save the configuration of the course details alongside
 *  the first learning activity that we should send to the user on launching the
 *    course
 */
export interface CoursePackage extends IObject
{
  /** The title of the course as provided by the course designer */
  title: string;
  
  /** The descroption of the course as provided by the course designer */
  description?: string;
  
  /** The id provided by the third party platform e.g. Articulate */
  externalId: string;
  
  /** A listing of objectives referenced by this block as defined by the 
   * course designer
   */
  objectives: CourseObjective[];

  /**  The first learning activity that we should send to the user on launching the course */
  firstAU: string;

  /** Language of the course as configured by the course designer */
  lang?: string;
}

/** A listing of objectives referenced by this block as defined by the 
 * course designer
 */
export interface CourseObjective {
  /** An autogenerated unique identifier of the course objective */
  id: string;
  /** The title of the course objective as provided by the course designer */
  title: string;
  /** The description of the course objective as provided by the course designer */
  description?: string;
}