// import { EnrolledEndUser } from '../../../../../../../model/convs-mgr/learners/src/lib/enrolled-learners.interface';

import { EnrolledEndUser } from "@app/model/convs-mgr/learners";

export const enrolledEndUsersMockData: EnrolledEndUser[] = [
  {
    name: 'John Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: '',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 1,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },
  {
    name: 'Jane Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: '',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 1,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },
  {
    name: 'Jane Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: '',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 1,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },  {
    name: 'Jane Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: 'class1',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 1,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },  {
    name: 'Jane Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: 'class1',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 1,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },  {
    name: 'Jane Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: 'class1',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 1,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },  {
    name: 'Jane Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: 'class1',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 1,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },  {
    name: 'Jane Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: 'class1',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 2,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },  {
    name: 'Jane Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: 'class1',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 1,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },  {
    name: 'Jane Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: 'class1',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 1,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },  {
    name: 'Jane Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: 'class1',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 1,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },  {
    name: 'Jane Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: 'class1',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 1,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },  {
    name: 'Jane Doe',
    phoneNumber: '1234567890',
    receipientId: 'xyz123',
    classId: 'class1',
    currentCourse: 'Course 1',
    modules: ['Module1', 'Module2'],
    lessons: ['Lesson1', 'Lesson2'],
    whatsappUserId: 'whatsappUser1',
    messengerUserId: 'messengerUser1',
    status: 1,
    assessmentResults: [],
    surveyResults: [],
    platformDetails: {
      whatsapp: { endUserId: 'whatsappUser1', contactID: 'whatsappContact1' },
      messenger: {
        endUserId: 'messengerUser1',
        contactID: 'messengerContact1',
      },
    },
  },
];
