export const collectionIds = [
  'orgs',
  'channels',
  'users',
  'end-users',
  'enrolled-end-users',
  'cursor',
  'messages',
  'bots',
  'stories',
  'surveys',
  'classes',
  'message-templates',
  'milestone-triggers',
  'modules',
  'scheduled-messages',
]