name: Create Release

'on':
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with: 
          name: Release ${{ github.ref }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
        env:
          GITHUB_REPOSITORY: italanta/elewa