name: Testing code
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  test-whatsapp-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - run: npm install

      - run: npx nx test functions-bot-engine-whatsapp