name: Run Tests
on: 
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node }}

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Runs tests on the nx projects affected by the Pull Request
      - name: Run tests
        id: tests
        run: npx nx affected --target=test