name: Run Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Runs tests on the nx projects affected by the Pull Request
      - name: Run tests
        id: tests
        run: npx nx affected --target=test

      - run: echo ${{ steps.tests.outputs }}
        if: always
        
      - name: Comment PR
        if: always()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave: