name: Testing code
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  test-whatsapp-parser:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node }}

      - run: npm install --legacy-peer-deps

      - run: npx nx test functions-bot-engine-whatsapp